apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timekeeper.fullname" . }}
  labels:
    {{- include "timekeeper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "timekeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timekeeper.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "timekeeper.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.http.port }}
              name: http
          env:
            - name: TIMEKEEPER_PORT
              value: "{{ .Values.service.http.port }}"
            {{- .Values.environment | toYaml | nindent 12 }}